Server:
    host: "localhost"
    Debug: true
    Port: 8080

Search:
    minimum_words: 3 # Minimum words in a row it can use to do loose search. The lower the more innacurate it is.
    accuracy_cutoff: 60 # Determine accuracy when using advanced search. 
